In [1]:
import pandas as pd

measures = pd.read_csv('hawaii_measurements.csv')
stations = pd.read_csv('hawaii_stations.csv')

In [19]:
measures.head(200)

         station        date  prcp  tobs
0    USC00519397  2010-01-01  0.08    65
1    USC00519397  2010-01-02  0.00    63
2    USC00519397  2010-01-03  0.00    74
3    USC00519397  2010-01-04  0.00    76
4    USC00519397  2010-01-06   NaN    73
5    USC00519397  2010-01-07  0.06    70
6    USC00519397  2010-01-08  0.00    64
7    USC00519397  2010-01-09  0.00    68
8    USC00519397  2010-01-10  0.00    73
9    USC00519397  2010-01-11  0.01    64
10   USC00519397  2010-01-12  0.00    61
11   USC00519397  2010-01-14  0.00    66
12   USC00519397  2010-01-15  0.00    65
13   USC00519397  2010-01-16  0.00    68
14   USC00519397  2010-01-17  0.00    64
15   USC00519397  2010-01-18  0.00    72
16   USC00519397  2010-01-19  0.00    66
17   USC00519397  2010-01-20  0.00    66
18   USC00519397  2010-01-21  0.00    69
19   USC00519397  2010-01-22  0.00    67
20   USC00519397  2010-01-23  0.00    67
21   USC00519397  2010-01-24  0.01    71
22   USC00519397  2010-01-25  0.00    67
23   USC00519397  2010-01-26  0.04    76
24   USC00519397  2010-01-27  0.12    68
25   USC00519397  2010-01-28  0.00    72
26   USC00519397  2010-01-30   NaN    70
27   USC00519397  2010-01-31  0.03    67
28   USC00519397  2010-02-01  0.01    66
29   USC00519397  2010-02-03   NaN    67
..           ...         ...   ...   ...
170  USC00519397  2010-07-08  0.03    76
171  USC00519397  2010-07-09  0.06    74
172  USC00519397  2010-07-10  0.09    76
173  USC00519397  2010-07-11  0.00    78
174  USC00519397  2010-07-12  0.00    77
175  USC00519397  2010-07-13  0.00    80
176  USC00519397  2010-07-16   NaN    78
177  USC00519397  2010-07-17  0.02    76
178  USC00519397  2010-07-18  0.00    77
179  USC00519397  2010-07-19  0.04    77
180  USC00519397  2010-07-21  0.00    80
181  USC00519397  2010-07-22  0.00    78
182  USC00519397  2010-07-24  0.00    80
183  USC00519397  2010-07-25  0.00    79
184  USC00519397  2010-07-26  0.00    78
185  USC00519397  2010-07-27  0.00    79
186  USC00519397  2010-07-28  0.00    78
187  USC00519397  2010-07-29  0.00    79
188  USC00519397  2010-07-30  0.00    78
189  USC00519397  2010-07-31  0.02    77
190  USC00519397  2010-08-01  0.04    77
191  USC00519397  2010-08-02  0.01    76
192  USC00519397  2010-08-03  0.02    77
193  USC00519397  2010-08-04  0.07    77
194  USC00519397  2010-08-05  0.08    75
195  USC00519397  2010-08-06  0.03    75
196  USC00519397  2010-08-07  0.00    80
197  USC00519397  2010-08-08  0.00    77
198  USC00519397  2010-08-09  0.00    78
199  USC00519397  2010-08-10  0.00    78

[200 rows x 4 columns]

In [20]:
measures.shape

(19550, 4)

In [21]:
stations.head()

,station,name,latitude,longitude,elevation
0,USC00519397,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
1,USC00513117,"KANEOHE 838.1, HI US",21.4234,-157.8015,14.6
2,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.5213,-157.8374,7.0
3,USC00517948,"PEARL CITY, HI US",21.3934,-157.9751,11.9
4,USC00518838,"UPPER WAHIAWA 874.3, HI US",21.4992,-158.0111,306.6

In [22]:
stations.shape

(9, 5)

In [23]:
measures.isnull().sum()

station       0
date          0
prcp       1447
tobs          0
dtype: int64

In [11]:
stations.isnull().sum()

station      0
name         0
latitude     0
longitude    0
elevation    0
dtype: int64

In [16]:
clean_stations = stations
clean_measures = measures.dropna()

In [17]:
clean_measures.shape

(18103, 4)

In [24]:
clean_stations.to_csv('clean_hawaii_stations.csv', index=False, header=True)
clean_measures.to_csv('clean_hawaii_measurements.csv', index=False, header=True)